version: '3.9'
services:
  apache:
    image: php:8.2-apache
    container_name: apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_DATABASE: lampdb
      MYSQL_USER: lampuser
      MYSQL_PASSWORD: lamppass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOTS: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
